title: Default
default_field: title
sections:
  main:
    title: Main
    fields:
      title:
        title: admin_title
        type: text
        size: col-12
      content:
        title: admin_content
        type: editor
        size: col-12
      template:
        title: admin_template
        type: template_select
        size: col-4
      visibility:
        title: admin_visibility
        type: visibility_select
        size: col-4
      date:
        title: admin_date
        type: text
        size: col-4
  seo:
    title: Seo
    fields:
      description:
        title: admin_description
        type: textarea
        size: col-12
  menu:
    title: Menu
    fields:
      menu_item_title:
        title: admin_menu_item_title
        type: text
        size: col-4
      menu_item_url:
        title: admin_menu_item_url
        type: text
        size: col-4
      menu_item_target:
        title: admin_menu_item_target
        type: select
        options:
          _self: _self
          _blank: _blank
          _parent: _parent
          _top: _top
        size: col-4
      menu_item_order:
        title: admin_menu_item_order
        type: text
        size: col-4
